Require beacon remove event be sent synchronously
IntellectualSites/FastAsyncWorldEdit-Adapters pull request #4
Opened 2021-07-10 20:17 UTC by dordsor21

We should still be removing beacons before we conduct the edit to the chunk, so must do some of the work ourselves and then fire the event/sound synchronously at the end (when players would know about it).

2021-07-10 20:36 UTC, NotMyFault approved these changes

2021-07-11 07:05 UTC, SirYwell requested changes
The event is paper only. We need `PaperLib.isPaper()` checks to guard against issues with missing classes on spigot (or start to have separate implementations, which would be useful in other places too but even more copy paste work)

2021-07-11 07:14 UTC, dordsor21 commented
> The event is paper only. We need `PaperLib.isPaper()` checks to guard against issues with missing classes on spigot (or start to have separate implementations, which would be useful in other places too but even more copy paste work)

Oh of course... I hadn't even thought of that. I don't have internet until tomorrow evening so if someone else wants to add the Paper check to the initial beacon check that would be quickest.

2021-07-11 07:41 UTC, NotMyFault commented
Speaking of PaperLib, we use `ChunkProviderServer#getChunkAtIfLoadedImmediately()` in some spots which is Paper only as well. Tho, this is out of the scope of the pr but I'll leave it here so we don't forget.

2021-07-12 11:21 UTC, SirYwell commented
This should do the trick. I didn't test it tho

2021-07-12 11:24 UTC, dordsor21 commented
I tested the PR on paper and it worked good. That should do it nicely, thanks

2021-07-12 11:30 UTC, SirYwell approved these changes

2021-07-12 11:30 UTC, merged