Handle synchronisation of generateTree method at the "lowest" level
IntellectualSites/FastAsyncWorldEdit-Adapters pull request #71
Opened 2022-06-11 21:03 UTC by dordsor21

- https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/1788

2022-06-11 21:10 UTC, NotMyFault approved these changes

2022-06-12 08:50 UTC, SirYwell requested changes
The comments apply for all versions I guess

2022-06-12 08:50 UTC, SirYwell commented on spigot_v1_16_R3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/FAWE_Spigot_v1_16_R3.java
> +                world.capturedBlockStates.clear();
I think the map should always be cleared (but copied before when returning)

2022-06-12 08:50 UTC, SirYwell commented on spigot_v1_16_R3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/FAWE_Spigot_v1_16_R3.java
> +        for (CraftBlockState craftBlockState : world.capturedBlockStates.values()) {
This should use the copied map (or we could also just copy the values instead)

2022-06-12 12:17 UTC, SirYwell requested changes

2022-06-12 12:17 UTC, SirYwell commented on spigot_v1_16_R3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/FAWE_Spigot_v1_16_R3.java
> +        if (placed == null) {
Without checking the return value of generateTree, placed won't be null.

2022-06-12 12:22 UTC, SirYwell approved these changes

2022-06-12 13:21 UTC, merged